### ISSUE TITLE
get_balance fails when account doesn't exist

### ISSUE THREAD

**Issue by evgenykuzyakov** [near-examples/FT#9]
https://github.com/near-examples/FT/blob/901145fdd67b9619452ab1afb5dade9b62bf015a/contracts/assemblyscript/nep21-basic/main.ts#L102

Why does the implementation need to fail instead of returning `0`?

If you write a contract that checks balance of a user, you now need to handle 2 cases. Does the response failed or returned a value. Instead of always succeed and rerturn.

**Comment by idea404** [comment]
Examples now in Rust and do return 0 when an account is not registered with the ft_contract
